name: Deploy to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: development

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
      MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
      MAILJET_SENDER_EMAIL: ${{ secrets.MAILJET_SENDER_EMAIL }}
      MAILJET_SENDER_NAME: ${{ secrets.MAILJET_SENDER_NAME }}
      ACCOUNT_VERIFICATION_KEY: ${{ secrets.ACCOUNT_VERIFICATION_KEY }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      OAUTH_STATE_STRING: ${{ secrets.OAUTH_STATE_STRING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.6

      - name: Build
        run: go build -o login-mobile-app-be

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: login-mobile-app-be
          path: login-mobile-app-be

      - name: Transfer to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: login-mobile-app-be
          target: /opt/login-mobile-app-be/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo systemctl stop login-mobile-app-be || true
            sudo systemctl start login-mobile-app-be
